# Tomcat 配置
server:
  port: 80

# 数据库 及 Redis 配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # password: [Redis客户端密码]
  datasource:
    url: 127.0.0.1
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: wanglong
    sql-script-encoding: utf-8
  mail:
    host: smtp.qq.com
    username: 1968155152@qq.com
    password: ahtfwhaprmyggjef
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false
          required: false

# Mybatis 配置
mybatis:
  config-location: classpath:/mybatis.xml

# Redis Key 前缀
redis:
  prefix:
    signUp: SIGN

# 本站信息
app:
  name: ictgu
  domain: www.triangleidea.com
